#!/bin/bash
# TODO(kirktdev): put a comment here to let people know how to test up the dev env
# 1. download third party jars
# 2. set up $JAVA_CLASS_PATH

# compile java
# TODO(kirktdev): relative path can?
javac -Xlint:deprecation \
    -sourcepath /Users/kirkt/Dropbox/github/java_tax/src \
    -cp $JAVA_CLASS_PATH \
    -d /Users/kirkt/Dropbox/github/java_tax/class \
    src/com/kirkkt/java/tax/forms/*.java \
    src/com/kirkkt/java/tax/forms/input/*.java
