#!/bin/bash

# compile java
# TODO(kirktdev): relative path can?
javac -Xlint:deprecation \
    -sourcepath /Users/kirkt/Dropbox/github/java_tax/src \
    -cp $JAVA_CLASS_PATH \
    -d /Users/kirkt/Dropbox/github/java_tax/class \
    src/com/kirkkt/java/tax/forms/*.java \
    src/com/kirkkt/java/tax/forms/input/*.java
